version: '3.9'

services:
  # Service MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    networks:
      - app_network
    environment:
      MONGO_INITDB_DATABASE: expenses_db
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"

  # Service backend Flask
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_backend
    depends_on:
      - mongo  # Le backend dépend de MongoDB
    environment:
      DB_URI: "mongodb://mongo:27017/expenses_db"  # Connexion MongoDB via service "mongo"
    networks:
      - app_network
    ports:
      - "5001:5001"  # Le backend écoute sur le port 5001

  # Service frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: html_frontend
    depends_on:
      - backend  # Le frontend dépend du backend
    networks:
      - app_network
    ports:
      - "80:80"  # Nginx écoute sur le port 80
    environment:
      - API_URL=http://backend:5001
      
networks:
  app_network:
    driver: bridge